### ISSUE TITLE
Avoid softkick on cdtv? 

### ISSUE THREAD

**Issue by timfel** [jotd666/jst#6]
Sorry if this is a dumb question - do I understand the code around https://github.com/jotd666/jst/blob/06315b162635ad767150429c09921addf05bef49/src/jst_whdinit.asm#L231 correctly that on a stock CDTV with 1.3 Kickstart ROM, I will still softkick kick1. 3 for slaves that declare so? And if so, would it make sense to skip this (or add an option to do so) on that machine to save some memory?

**Comment by jotd666** [comment]
Hi,

Softkick is done so we can patch kickstart 1.3 in ram to redirect
floppy/hard drive reads & other stuff. We can't use KS 1.3 rom directly,
sorry! I'm aware that it makes JST unusable on CDTV for kickstart-dependent
slaves. Only slaves that will work on CDTV are the ones that need 512k and
which have small data size to be preloaded. Someone created a compilation
with those titles some time ago. One could play arkanoid for instance.

bye


Le ven. 15 mars 2024 à 22:38, Tim Felgentreff ***@***.***> a
écrit :

**Comment by timfel** [comment]
Thank you for the explanation, I learned something 🙂
