### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by LinuxJedi** [jotd666/jst#7]
The source here is available, but it will be difficult to anyone to contribute to it, or even install it in some regions, without a license attached. Could you please add a license file to define what license it is? (even if it is commercial / no license).

**Comment by jotd666** [comment]
Would a MIT licence work?


Le lun. 12 août 2024 à 10:54, Andrew Hutchings ***@***.***> a
écrit :

**Comment by LinuxJedi** [comment]
Yep. MIT would be perfect 🙂

**Comment by jotd666** [comment]
done!
