### ISSUE TITLE
Harlequin

### ISSUE THREAD

**Issue by ghost** [jotd666/jst#9]
hello does Harlequin work with JST? and does it need any devs or libraries to work? 
as i wanted to hopefully run it with 1mb chip ram and no fast ram, is it possible?
thanks

**Comment by jotd666** [comment]
Harlequin runs with JST, but it requires at least 2MB of memory. There are 2 1mb disks to load, so it cannot be preloaded in 1MB or even OS switch it with that small memory.

whdload won't be able to run it either with so little memory.

**Comment by ghost** [comment]
@

> Harlequin runs with JST, but it requires at least 2MB of memory. There are 2 1mb disks to load, so it cannot be preloaded in 1MB or even OS switch it with that small memory.
> 
> whdload won't be able to run it either with so little memory.

obviously WHDLoad can't if JST can't, as WHDLoad has higher system requirements, pointlessly stating the obvious

**Comment by jotd666** [comment]
"pointlessly stating the obvious" seriously?
